services:
  postgres:
    image: postgres:16-alpine
    container_name: igris_postgres
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=igris
    volumes:
      - igris_pg_data:/var/lib/postgresql/data

  influxdb:
    image: influxdb:2.7-alpine
    container_name: igris_influxdb
    restart: always
    ports:
      - '8086:8086'
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=igris
      - DOCKER_INFLUXDB_INIT_BUCKET=logs
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=supersecrettoken123
    volumes:
      - influxdb_data:/var/lib/influxdb2

  grafana: 
    image: grafana/grafana:latest
    container_name: igris_grafana
    restart: always
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=adminpassword
    depends_on:
      - influxdb
    volumes:
      - grafana_data:/var/lib/grafana


  api:
    build:
      context: .
      dockerfile: infrastructure/docker/api/Dockerfile
    container_name: igris_api
    ports:
      - '3333:3333'
    environment:
      - DATABASE_URL=postgresql://docker:docker@postgres:5432/igris
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=supersecrettoken123
      - INFLUX_ORG=igris
      - INFLUX_BUCKET=logs
    depends_on:
      - postgres
      - influxdb

  ai-engine:
    build:
      context: .
      dockerfile: infrastructure/docker/ai-engine/Dockerfile
    container_name: igris_ai_engine
    environment:
      - INFLUX_URL=http://influxdb:8086
      - API_URL=http://api:3333
    depends_on:
      - influxdb
      - api

  web:
    build:
      context: .
      dockerfile: infrastructure/docker/web/Dockerfile
    container_name: igris_web
    ports:
      - '5173:5173'
    depends_on:
      - api

  agent:
    build:
      context: .
      dockerfile: infrastructure/docker/agent/Dockerfile
    container_name: igris_agent
    privileged: true 
    pid: "host"
    environment:
      - API_URL=http://api:3333/logs
      - SERVER_ID=8ea5849b-296b-430d-a373-75c2e9a1f4c1
    depends_on:
      - api

volumes:
  igris_pg_data:
  influxdb_data: 
  grafana_data: